# path to user-data for CVAT
cvat_credentials_path: private/cvat.yml

export_format: YOLO 1.1

output_dir: /ENOT22/GSN/labeling

include_images:

#table_url: https://docs.google.com/spreadsheets/d/15bKXNUphGce9wvCLj0upnaHOG4Fuu25FzoUVlw12OWQ/edit?usp=sharing
table_url: https://docs.google.com/spreadsheets/d/1qVdDsfiTCZKMDyQsFrWhE4tmJVCuIoZ0CIWw05UCaRw/edit?usp=sharing
table_credentials_path: private/credentials.json

date: 10.10.2025

cost_diff_box: 0.4
cost_diff_box_increased: 0.6
cost_new_box: 0.8
cost_new_box_increased: 1
box_change_low_threshold: 0.1
box_change_high_threshold: 0.7

salary_table_url: https://docs.google.com/spreadsheets/d/14qPTLtv_VWEVQZJYm4mLuM0A-uiqzpwDpMrB_1S6OHg/edit?usp=sharing