# path to user-data for CVAT
cvat_credentials_path: private/cvat.yml
project_id: 9

# path to root dir in /mnt/cvat_share
share_path: shestakov/test_data

# path to txt-file with directory names
path_to_data_names: