# path to user-data for CVAT
cvat_credentials_path: private/cvat.yml
project_id: 25

# path to root dir in /mnt/cvat_share
share_path: building_machines_orlovka_25

# path to txt-file with directory names (if is empty, you will upload all directories in share_path)
path_to_data_names: data/data_names.txt

table_url:
sheet_id:
table_credentials_path:
column_names: